import { Roboto } from 'next/font/google'
import '../styles/global.scss'

const roboto = Roboto({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'ig.news',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
